name: Validate Translations

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  main:
    name: Validate Translations
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Clone SwiftPolyglot
        run: git clone https://github.com/appdecostudio/SwiftPolyglot.git --branch=1.1.0 ../SwiftPolyglot

      - name: validate translations
        run: |
          swift build --package-path ../SwiftPolyglot --configuration release
          swift run --package-path ../SwiftPolyglot swiftpolyglot en --error-on-missing