name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build Xcode
      run: xcodebuild clean build -project "Code Relay/Code Relay.xcodeproj" -scheme "Code Relay" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
