name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Xcode Project
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Navigate to the main directory
        run: cd "Code Relay"
      
      - name: Build
        run: |
          xcodebuild clean build analyze -scheme "Code Relay" | xcpretty && exit ${PIPESTATUS[0]}
